### ISSUE TITLE
Vue CLI v4.5.9 创建项目出错了

### ISSUE THREAD

**Issue by duoduoxi** [daodao97/oms#1]
错误信息如下：
`D:\0study>vue create --preset E:\yuanma\rock-admin-master rock-admin

Vue CLI v4.5.9
✨  Creating project in D:\0study\rock-admin.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

> ejs@2.7.4 postinstall D:\0study\rock-admin\node_modules\ejs
> node ./postinstall.js

added 1050 packages from 906 contributors in 153.73s

56 packages are looking for funding
  run `npm fund` for details

🚀  Invoking generators...

Preset options:
 WARN  conflicting versions for project dependency "vue":

- ^2.6.11 injected by generator "@vue/cli-service"
- ^3.0.0 injected by generator "E:\yuanma\rock-admin-master"

Using newer version (^3.0.0), but this may cause build errors.
 ERROR  ReferenceError: ejs:7
    5|   <meta http-equiv="X-UA-Compatible" content="IE=edge">
    6|   <meta name="viewport" content="width=device-width,initial-scale=1.0">
 >> 7|   <link rel="icon" href="<%= BASE_URL %>favicon.ico">
    8|   <title><%= htmlWebpackPlugin.options.title %></title>
    9|   <style>
    10|     #preloader {

BASE_URL is not defined
ReferenceError: ejs:7
    5|   <meta http-equiv="X-UA-Compatible" content="IE=edge">
    6|   <meta name="viewport" content="width=device-width,initial-scale=1.0">
 >> 7|   <link rel="icon" href="<%= BASE_URL %>favicon.ico">
    8|   <title><%= htmlWebpackPlugin.options.title %></title>
    9|   <style>
    10|     #preloader {

BASE_URL is not defined
    at eval (eval at compile (D:\nodejs\node_global\node_modules\@vue\cli\node_modules\ejs\lib\ejs.js:652:12), <anonymous>:12:26)
    at anonymous (D:\nodejs\node_global\node_modules\@vue\cli\node_modules\ejs\lib\ejs.js:682:17)
    at Object.exports.render (D:\nodejs\node_global\node_modules\@vue\cli\node_modules\ejs\lib\ejs.js:419:37)
    at renderFile (D:\nodejs\node_global\node_modules\@vue\cli\lib\GeneratorAPI.js:534:14)
    at D:\nodejs\node_global\node_modules\@vue\cli\lib\GeneratorAPI.js:300:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Generator.resolveFiles (D:\nodejs\node_global\node_modules\@vue\cli\lib\Generator.js:268:7)
    at async Generator.generate (D:\nodejs\node_global\node_modules\@vue\cli\lib\Generator.js:175:5)
    at async Creator.create (D:\nodejs\node_global\node_modules\@vue\cli\lib\Creator.js:229:5)
    at async create (D:\nodejs\node_global\node_modules\@vue\cli\lib\create.js:72:3)
`

谷歌也没找到解决方案，要怎么处理呢？谢谢。

**Comment by daodao97** [comment]
上述报错的具体原因是 `webpack` 的模板变量替换, `template/public/index.html` 为 `presets` 生成是的模板文件, 其中的 `<% 
BASE_URL %>` 等 `webpack`变量不需转义, 需要原样输出到目标项目中, 详细可见 [template/public/index.html](https://github.com/daodao97/rock-admin/blob/master/template/public/index.html) 

项目还在快速开发中, 更改较快, 现可用 `vue create --preset daodao97/rock-admin my-admin` 创建模板项目

也可以使用 [example](https://github.com/daodao97/rock-admin/tree/master/example) 目录, 启动样例项目.
